clear
make OSD=sdl SOURCES=src/mame/drivers/cps3.cpp TOOLS=0 IGNORE_GIT=1 DEBUG=1 SYMBOLS=1 OPTIMIZE=0 USE_QTDEBUG=0 USE_LIBSDL=1 USE_SYSTEM_LIB_EXPAT=1 USE_SYSTEM_LIB_ZLIB=1 USE_SYSTEM_LIB_FLAC=1 USE_SYSTEM_LIB_SQLITE3=1 USE_SYSTEM_LIB_PORTMIDI=1 USE_SYSTEM_LIB_PORTAUDIO=1 USE_SYSTEM_LIB_UTF8PROC=1 USE_SYSTEM_LIB_GLM=1 USE_SYSTEM_LIB_RAPIDJSON=1 USE_SYSTEM_LIB_PUGIXML=1 -j3
