@startuml
skinparam Shadowing false
skinparam LineType ortho
skinparam ArrowColor black

skinparam class {
    BackgroundColor WhiteSmoke
    BorderColor black
}

class renderer_sdl2 {
	-SDL_Renderer sdl_renderer
	
	+int create()
	+render_primitive[] get_primitives()    
	+int draw(const int update)
	{static} +void init(running_machine machine)
	{static} +void exit()
}

enum primitive_type
{
	LINE
	QUAD
}

class render_primitive {
	+render_bounds bounds
	+primitive_type type
	+render_color color
	+render_texinfo texture
	+render_quad_texuv texcoords
}

renderer_sdl2 -l-|> osd_renderer
renderer_sdl2 -r- render_primitive
renderer_sdl2 -l- SDL_Renderer
render_primitive -r- primitive_type

@enduml
