@startuml
skinparam Shadowing false
skinparam LineType ortho
skinparam ArrowColor black

skinparam class {
    BackgroundColor WhiteSmoke
    BorderColor black
}

class renderer_sdl2 {
	-SDL_Renderer sdl_renderer
	
	+int create()
	+render_primitive[] get_primitives()    
	+int draw(const int update)
	{static} +void init(running_machine machine)
	{static} +void exit()
}

enum primitive_type
{
	LINE
	QUAD
}

class render_primitive {
	+render_bounds bounds
	+primitive_type type
	+render_color color
	+render_texinfo texture
	+render_quad_texuv texcoords
}

class osd_renderer {
    -osd_window  m_window
    +osd_window assert_window()
    {abstract} +int create()
    {abstract} +render_primitive[] get_primitives()
    {abstract} +int draw(const int update)
    {static} +osd_renderer make_for_type(int mode, osd_window window, int extra_flags)
}

class osd_window {
    +HDC m_dc
    +render_primitive[] m_primlist
    +osd_renderer renderer()        
    {abstract} +render_target target()    
    {abstract} +running_machine machine()
    {abstract} +void update()    
}

package SDL {
	class SDL_Renderer
}

renderer_sdl2 -l-|> osd_renderer
renderer_sdl2 -r- SDL_Renderer

osd_renderer -l- osd_window
osd_window -l- render_primitive
render_primitive -l- primitive_type

@enduml