@startuml
skinparam Shadowing false
skinparam LineType ortho
skinparam ArrowColor black
skinparam nodesep 15
skinparam ranksep 30

skinparam class {
    BackgroundColor WhiteSmoke
    BorderColor black
}


entity Win32
entity DirectX
entity X11
package SDL {
	class SDL_Event
	class SDL_Joystick
}


class event_based_device<TEvent> {
	-queue<TEvent> event_queue
	{abstract} #void process_event(TEvent e)
	+void queue_events(TEvent[] events, int count)
}

class device_info {
	-string id
	-string name
	-running_machine machine
	-input_module module
	{abstract} +void poll()
	{abstract} +void reset()
}

event_based_device --|> device_info

class sdl_device<SDL_Event>

sdl_peripheral_device --|> sdl_device
sdl_peripheral_device -- SDL_Joystick
sdl_device -- SDL_Event

class win32_peripheral_device<EventArgs>

class x11_input_device<XEvent> 
x11_input_device --|> event_based_device

xinput_peripheral_device --|> x11_input_device

dinput_device --|> device_info
dinput_peripheral_device --|> dinput_device

sdl_device -u-|> event_based_device
win32_peripheral_device --|> event_based_device

X11 -d- xinput_peripheral_device
Win32 -d- win32_peripheral_device
DirectX -d- dinput_peripheral_device
@enduml
